### PR TITLE
Create Hebrew translation

### PR DESCRIPTION
**Pull request by Eng2Heb**

### CODE REVIEW

**Comment by midraal** [comment]
think i have everything in strings.po file now, for next release
https://gist.github.com/midraal/e55e92c0c439645ddcec450ee47cb89e

**Comment by Eng2Heb** [comment]
I have done the strings.po. in the Gist as a comment  (there is no upload option or creating new file)
Do you want me to update the code here or just leave it there?

**Comment by Eng2Heb** [comment]
Done.
https://gist.github.com/Eng2Heb/a5c8802ad7228bd403f687f80792157a

**Comment by midraal** [comment]
thank you, it's in latest dev version

**Pull request closed without merging**
